module.exports = (pageObjects, entries) => {
    pageObjects
        .click('.bm-burger-button')
        .waitForElementVisible('p[name="enterOption"]', 1000)
        .click('p[name="enterOption"]')
        .setValue('@Header', entries.Header)
        .setValue('@MKE', entries.MKE)
        .setValue('@ORI', entries.ORI)
        .setValue('@Name', entries.Name)
        //.setValue('@Sex', entries.Sex)
        .click(entries.Sex)
        //.setValue('@Race', entries.Race)
        .click(entries.Race)
        .setValue('@Height', entries.Height)
        .setValue('@Weight', entries.Weight)
        .setValue('@Hair', entries.Hair)
        .setValue('@Offense', entries.Offense)
        .setValue('@DOW', entries.DOW)
        .setValue('@OLN', entries.OLN)
        .setValue('@OLS', entries.OLS)
        .setValue('@OLD', entries.OLD)
        .setValue('@LIC', entries.LIC)
        .setValue('@LIS', entries.LIS)
        .setValue('@LID', entries.LID)
        .click('@submitBtn')
    pageObjects
        .expect.element('@queryBody').text.to.contain(entries.results).after(500)
    }